#!/bin/bash
# Launch the v1.3 open-set supervised runs:
#   1. open_set_only       -- v1.3 from scratch, open-set supervised dataset only.
#   2. open_set_osm        -- v1.3 from scratch, osm_sampling + open-set.
#   3. open_set_post_train -- the v1.3 base checkpoint, post-trained on
#                             osm_sampling + open-set: probe-only phase (backbone
#                             frozen), then backbone phase (probe frozen).
#   Probe variants of open_set_only (see open_set_base.build_model_config):
#   4. open_set_only_mlp   -- shared 2-layer MLP trunk before the heads.
#   5. open_set_only_text  -- CLIP-style cosine logits against frozen class text
#                             embeddings (reads class_text_embeddings.npy from weka, see
#                             open_set_base.CLASS_TEXT_EMBEDDINGS_PATH; generated by
#                             open_set_segmentation_data.embed_class_names).
#   6. open_set_only_dsbal -- per-dataset temperature-balanced loss (tau = 0.5).
#
# All inherit the v1.3 release recipe (Perceiver registers + map supervision +
# distilled student, single-forward LatentMIM, DDP + bf16, student in-loop evals as
# separate Beaker jobs) and add the open-set probe loss on the register grid.
#
# open_set_post_train needs the converted v1.3 base weights (once):
#   python scripts/official/v1_3/convert_legacy_checkpoint.py \
#     /weka/dfive-default/olmoearth_pretrain/checkpoints/gabrielt/regbtl_v1_2_gdyn_d768_proj128lin_sup768_w1_newsamp_psuniform_stunorm_mlpgram1/step667200 \
#     /weka/dfive-default/olmoearth_pretrain/checkpoints/gabrielt/regbtl_v1_2_gdyn_d768_proj128lin_sup768_w1_newsamp_psuniform_stunorm_mlpgram1/step667200_converted
#
# Launch requires a clean tree pushed to the remote.
set -e

LAUNCH_ARGS="--launch.num_gpus=8 --launch.priority=urgent --launch.clusters=[ai2/jupiter,ai2/ceres]"

if [ "$#" -eq 0 ]; then
    echo "usage: $0 {open_set_only|open_set_osm|open_set_post_train|open_set_only_mlp|open_set_only_text|open_set_only_dsbal} [...]"
    exit 1
fi

for script in "$@"; do
    python scripts/official/v1_3/$script.py launch $script ai2/jupiter $LAUNCH_ARGS
done
