"""Register the 1..12-month temporal ablation for the OlmoEarth PLANTEUR probe.

The ablation asks how much of the agricultural year the encoder needs to see.
Each arm keeps the FIRST N monthly S2 mosaics (mo01..moN) and drops the rest --
mo01 is 2018-09, so arm N answers "can you classify N months into the season?",
which is the operationally useful direction. (Evenly-spaced subsampling would
instead isolate observation COUNT from season; that is a different experiment
and is not what this one measures.)

Arms are cloned from pastis2_drom_bg8void -- the exact dataset behind the
published 35.02 S2 probe -- with only the sentinel2_l2a layer list truncated.
N=12 is therefore byte-identical to the base config, so it needs no new arm:
the published number IS the N=12 point, and that makes the top of the curve a
control rather than a twelfth run.
"""
import copy, json, os, re, sys

REPO = "/weka/dfive-default/piperw/dev/olmoearth_pretrain"
CFG = f"{REPO}/data/rslearn_dataset_configs"
REG = f"{REPO}/olmoearth_pretrain/evals/studio_ingest/registry.json"
EVALS = f"{REPO}/olmoearth_pretrain/internal/all_evals.py"
BASE = "pastis2_drom_bg8void"
MONTHS = range(1, 12)          # 1..11; 12 is the published base run


def log(m): print(m, flush=True)


# ---- 1. dataset config dirs -----------------------------------------------
src_yaml = f"{CFG}/{BASE}/model.yaml"
raw = open(src_yaml).read()
all_layers = [f"          - sentinel2_l2a_mo{m:02d}" for m in range(1, 13)]
block = "\n".join(all_layers)
assert block in raw, "the 12 sentinel2_l2a month layers are not contiguous in model.yaml"

for n in MONTHS:
    name = f"{BASE}_mo{n:02d}"
    d = f"{CFG}/{name}"
    os.makedirs(d, exist_ok=True)
    keep = "\n".join(all_layers[:n])
    s = raw.replace(block, keep)
    # every dropped month must really be gone, and every kept one still present
    for m in range(1, 13):
        tok = f"sentinel2_l2a_mo{m:02d}"
        assert (tok in s) == (m <= n), f"{name}: {tok} presence wrong"
    s = (f"# AUTO-GENERATED temporal-ablation arm of {BASE}: first {n} monthly S2\n"
         f"# mosaic{'s' if n > 1 else ''} (mo01..mo{n:02d}), later months dropped.\n"
         f"# Generated by gen_temporal_ablation.py -- edit that, not this.\n") + s
    open(f"{d}/model.yaml", "w").write(s)
log(f"  wrote {len(list(MONTHS))} config dirs")

# ---- 2. registry entries ---------------------------------------------------
reg = json.load(open(REG))
base_entry = reg["datasets"][BASE]
n_new = 0
for n in MONTHS:
    name = f"{BASE}_mo{n:02d}"
    e = copy.deepcopy(base_entry)
    e["name"] = name
    e["config_repo_dir"] = f"data/rslearn_dataset_configs/{name}"
    e["num_timesteps"] = n
    # S2 only: the other modalities keep their own (unablated) cadence, so
    # leaving them declared would let a task silently mix a 12-step S1 stack
    # into what is meant to be an N-month experiment.
    e["modalities"] = ["sentinel2_l2a"]
    e["norm_stats"] = {"sentinel2_l2a": base_entry["norm_stats"]["sentinel2_l2a"]}
    if name not in reg["datasets"]:
        n_new += 1
    reg["datasets"][name] = e
json.dump(reg, open(REG, "w"), indent=2, sort_keys=True, ensure_ascii=False)
open(REG, "a").write("\n")
log(f"  registry: +{n_new} entries ({len(reg['datasets'])} total)")

# ---- 3. tasks in all_evals.py ---------------------------------------------
src = open(EVALS).read()
A, B = "            # TEMPORAL-ABLATION-START\n", "            # TEMPORAL-ABLATION-END\n"
body = "".join(
    f'            f"{BASE}_mo{n:02d}_ws{{_ws}}_ps1_sentinel2": _pastis_ps1_task(\n'
    f"                [Modality.SENTINEL2_L2A.name],\n"
    f"                window_size=_ws,\n"
    f'                dataset="{BASE}_mo{n:02d}",\n'
    f"            ),\n"
    for n in MONTHS
)
head = ("            # Temporal ablation: the same S2 probe over the first N monthly\n"
        "            # mosaics, N=1..11. N=12 is pastis2_drom_bg8void_ws16_ps1_sentinel2\n"
        "            # above -- the published 35.02 -- so it is the curve's control, not\n"
        "            # a twelfth registration.\n")
blk = A + head + body + B
if A in src:
    src = re.sub(re.escape(A) + r".*?" + re.escape(B), lambda _: blk, src, flags=re.S)
else:
    anchor = ('            f"pastis2_drom_bg8void_ws{_ws}_ps1_sentinel1_sentinel2_landsat": '
              "_pastis_ps1_task(\n"
              "                [\n"
              "                    Modality.SENTINEL1.name,\n"
              "                    Modality.SENTINEL2_L2A.name,\n"
              "                    Modality.LANDSAT.name,\n"
              "                ],\n"
              "                window_size=_ws,\n"
              '                dataset="pastis2_drom_bg8void",\n'
              "            ),\n")
    assert anchor in src, "all_evals anchor not found"
    src = src.replace(anchor, anchor + blk, 1)
open(EVALS, "w").write(src)
import ast; ast.parse(src)
log(f"  all_evals.py: {src.count('_mo%02d_ws' % 1)} mo01 task, "
    f"{sum(src.count('_mo%02d_ws' % n) for n in MONTHS)} ablation tasks total")
log("GEN_TEMPORAL_OK")
